#!/usr/bin/env python
# getncdimlen
# cory.r.martin@noaa.gov
# 2019-10-17
# script to return length of requested dimension
# for specified netCDF file
import argparse

def get_ncdims(ncfile):
  """ get_ncdims(ncfile)
   - function to return dictionary of netCDF file dimensions and their lengths
   input: ncfile - string to path to netCDF file
   output: ncdims - dictionary where key is the name of a dimension and the
                    value is the length of that dimension

               ex:  ncdims['pfull'] = 127
  """
  import netCDF4 as nc
  ncf = nc.Dataset(ncfile)
  ncdims = {}
  for d in ncf.dimensions.keys():
    ncdims[d] = int(len(ncf.dimensions[d]))
  ncf.close()

  return ncdims

if __name__ == '__main__':
  parser = argparse.ArgumentParser(
           description='Get length of dimension specified from a FV3GFS netCDF file')
  parser.add_argument('ncfile', help='path to input netCDF file', type=str)
  parser.add_argument('dimname', help='name of dimension (ex: grid_xt)', type=str)
  args = parser.parse_args()
  FileDims = get_ncdims(args.ncfile)
  print(FileDims[args.dimname])
