#!/usr/bin/env python
# gfsnc2gctl
# script to generate a GrADS control file
# for a given FV3GFS netCDF Gaussian history file
# Cory.R.Martin@noaa.gov
# October 18, 2019
import netCDF4 as nc
import argparse
import numpy as np

def gfsnc2gctl(ncfile, ctlfile):
  # open the netCDF file
  ncf = nc.Dataset(ncfile)

if __name__ == '__main__':
  parser = argparse.ArgumentParser(
           description = 'This Python-based utility will read
                          a FV3GFS netCDF history file and produce
                          a GrADS control file')
  parser.add_argument('ncfile', help='path to netCDF file to process', type=str)
  parser.add_argument('ctlfile', help='path to output GrADS control file', type=str)
  args = parser.parse_args()
  gfsnc2gctl(args.ncfile, args.ctlfile)
